name: Build website

on: [push]

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Site
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: AsgerNoer
        reponame: AsgerNoer
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
        cname: asgernoer.dk
        gitemail: ${ secrets.EMAIL }